-- MySQL Script generated by MySQL Workbench
-- Wed Oct 25 20:54:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shift_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shift_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shift_db` DEFAULT CHARACTER SET utf8 ;
USE `shift_db` ;

-- -----------------------------------------------------
-- Table `shift_db`.`facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shift_db`.`facility` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shift_db`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shift_db`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shift_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shift_db`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(90) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `facility_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  `deleted` TINYINT(1) NOT NULL,
  `password_change_required` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_user_facility_idx` (`facility_id` ASC) VISIBLE,
  INDEX `fk_user_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_facility`
    FOREIGN KEY (`facility_id`)
    REFERENCES `shift_db`.`facility` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `shift_db`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shift_db`.`subject_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shift_db`.`subject_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shift_db`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shift_db`.`course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shift_db`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shift_db`.`subject` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(150) NULL,
  `day` VARCHAR(10) NOT NULL,
  `start` TIME NOT NULL,
  `end` TIME NOT NULL,
  `classroom` VARCHAR(8) NOT NULL,
  `user_id` INT NOT NULL,
  `start_day` DATE NOT NULL,
  `end_day` DATE NOT NULL,
  `subject_type_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subject_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_subject_subject_type1_idx` (`subject_type_id` ASC) VISIBLE,
  INDEX `fk_subject_course1_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_subject_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `shift_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subject_subject_type1`
    FOREIGN KEY (`subject_type_id`)
    REFERENCES `shift_db`.`subject_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subject_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `shift_db`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shift_db`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shift_db`.`request` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `issue_date` DATETIME NOT NULL,
  `comment` VARCHAR(150) NULL,
  `subject_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_request_subject1_idx` (`subject_id` ASC) VISIBLE,
  INDEX `fk_request_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_request_subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `shift_db`.`subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `shift_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shift_db`.`replacement_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shift_db`.`replacement_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shift_db`.`replacement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shift_db`.`replacement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `request_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `replacement_status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_replacement_request1_idx` (`request_id` ASC) VISIBLE,
  INDEX `fk_replacement_subject1_idx` (`subject_id` ASC) VISIBLE,
  INDEX `fk_replacement_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_replacement_replacement_status1_idx` (`replacement_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_replacement_request1`
    FOREIGN KEY (`request_id`)
    REFERENCES `shift_db`.`request` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_replacement_subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `shift_db`.`subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_replacement_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `shift_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_replacement_replacement_status1`
    FOREIGN KEY (`replacement_status_id`)
    REFERENCES `shift_db`.`replacement_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shift_db`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shift_db`.`notification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_date` DATETIME NOT NULL,
  `content` LONGTEXT NOT NULL,
  `user_id` INT NOT NULL,
  `request_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notification_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_notification_request1_idx` (`request_id` ASC) VISIBLE,
  CONSTRAINT `fk_notification_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `shift_db`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notification_request1`
    FOREIGN KEY (`request_id`)
    REFERENCES `shift_db`.`request` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
